# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "terraform-state-v2"
    key                  = "subscriptions/Azure for Students/resource-groups/terra-v2/buckets/k8s-ws-bkt/terraform.tfstate"
    resource_group_name  = "terraform-state"
    storage_account_name = "k8sbcstatestorage"
    subscription_id      = "1a9a1e48-a543-431b-95a7-abde30c447a5"
  }
}
